2022-01-09 18:22:22,913 INFO    MainThread:17722 [internal.py:wandb_internal():90] W&B internal server running at pid: 17722, started at: 2022-01-09 18:22:22.913157
2022-01-09 18:22:22,917 INFO    WriterThread:17722 [datastore.py:open_for_write():77] open: /content/tbcnn/wandb/offline-run-20220109_182221-2o1v4aoj/run-2o1v4aoj.wandb
2022-01-09 18:22:22,917 DEBUG   HandlerThread:17722 [handler.py:handle_request():130] handle_request: run_start
2022-01-09 18:22:25,685 DEBUG   HandlerThread:17722 [meta.py:__init__():40] meta init
2022-01-09 18:22:25,685 DEBUG   HandlerThread:17722 [meta.py:__init__():54] meta init done
2022-01-09 18:22:25,685 DEBUG   HandlerThread:17722 [meta.py:probe():214] probe
2022-01-09 18:22:25,687 DEBUG   HandlerThread:17722 [meta.py:_setup_git():204] setup git
2022-01-09 18:22:25,712 DEBUG   HandlerThread:17722 [meta.py:_setup_git():211] setup git done
2022-01-09 18:22:25,712 DEBUG   HandlerThread:17722 [meta.py:_save_pip():58] save pip
2022-01-09 18:22:25,713 DEBUG   HandlerThread:17722 [meta.py:_save_pip():72] save pip done
2022-01-09 18:22:25,726 DEBUG   HandlerThread:17722 [meta.py:probe():252] probe done
2022-01-09 18:23:27,479 WARNING MainThread:17722 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-01-09 18:23:31,164 WARNING MainThread:17722 [internal.py:wandb_internal():146] Internal process interrupt: 2
2022-01-09 18:23:31,164 ERROR   MainThread:17722 [internal.py:wandb_internal():149] Internal process interrupted.
2022-01-09 18:23:31,924 INFO    WriterThread:17722 [datastore.py:close():281] close: /content/tbcnn/wandb/offline-run-20220109_182221-2o1v4aoj/run-2o1v4aoj.wandb
2022-01-09 18:23:31,953 INFO    HandlerThread:17722 [handler.py:finish():731] shutting down handler
2022-01-09 18:23:31,987 INFO    SenderThread:17722 [sender.py:finish():1070] shutting down sender
2022-01-09 18:23:32,003 INFO    MainThread:17722 [internal.py:handle_exit():77] Internal process exited
