2022-01-09 18:32:56,820 INFO    MainThread:18641 [internal.py:wandb_internal():90] W&B internal server running at pid: 18641, started at: 2022-01-09 18:32:56.820466
2022-01-09 18:32:56,825 INFO    WriterThread:18641 [datastore.py:open_for_write():77] open: /content/tbcnn/wandb/offline-run-20220109_183255-2ogxsg45/run-2ogxsg45.wandb
2022-01-09 18:32:56,827 DEBUG   HandlerThread:18641 [handler.py:handle_request():130] handle_request: run_start
2022-01-09 18:32:59,651 DEBUG   HandlerThread:18641 [meta.py:__init__():40] meta init
2022-01-09 18:32:59,651 DEBUG   HandlerThread:18641 [meta.py:__init__():54] meta init done
2022-01-09 18:32:59,651 DEBUG   HandlerThread:18641 [meta.py:probe():214] probe
2022-01-09 18:32:59,655 DEBUG   HandlerThread:18641 [meta.py:_setup_git():204] setup git
2022-01-09 18:32:59,685 DEBUG   HandlerThread:18641 [meta.py:_setup_git():211] setup git done
2022-01-09 18:32:59,685 DEBUG   HandlerThread:18641 [meta.py:_save_pip():58] save pip
2022-01-09 18:32:59,686 DEBUG   HandlerThread:18641 [meta.py:_save_pip():72] save pip done
2022-01-09 18:32:59,686 DEBUG   HandlerThread:18641 [meta.py:probe():252] probe done
2022-01-09 18:37:03,766 WARNING MainThread:18641 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-01-09 18:37:05,340 WARNING MainThread:18641 [internal.py:wandb_internal():146] Internal process interrupt: 2
2022-01-09 18:37:05,340 ERROR   MainThread:18641 [internal.py:wandb_internal():149] Internal process interrupted.
2022-01-09 18:37:05,383 INFO    WriterThread:18641 [datastore.py:close():281] close: /content/tbcnn/wandb/offline-run-20220109_183255-2ogxsg45/run-2ogxsg45.wandb
2022-01-09 18:37:05,389 INFO    HandlerThread:18641 [handler.py:finish():731] shutting down handler
2022-01-09 18:37:05,883 INFO    SenderThread:18641 [sender.py:finish():1070] shutting down sender
2022-01-09 18:37:05,898 INFO    MainThread:18641 [internal.py:handle_exit():77] Internal process exited
