2022-01-09 18:44:15,774 INFO    MainThread:20178 [internal.py:wandb_internal():90] W&B internal server running at pid: 20178, started at: 2022-01-09 18:44:15.774612
2022-01-09 18:44:15,778 INFO    WriterThread:20178 [datastore.py:open_for_write():77] open: /content/tbcnn/wandb/offline-run-20220109_184414-1fylxmq7/run-1fylxmq7.wandb
2022-01-09 18:44:15,779 DEBUG   HandlerThread:20178 [handler.py:handle_request():130] handle_request: run_start
2022-01-09 18:44:18,612 DEBUG   HandlerThread:20178 [meta.py:__init__():40] meta init
2022-01-09 18:44:18,612 DEBUG   HandlerThread:20178 [meta.py:__init__():54] meta init done
2022-01-09 18:44:18,612 DEBUG   HandlerThread:20178 [meta.py:probe():214] probe
2022-01-09 18:44:18,615 DEBUG   HandlerThread:20178 [meta.py:_setup_git():204] setup git
2022-01-09 18:44:18,644 DEBUG   HandlerThread:20178 [meta.py:_setup_git():211] setup git done
2022-01-09 18:44:18,644 DEBUG   HandlerThread:20178 [meta.py:_save_pip():58] save pip
2022-01-09 18:44:18,645 DEBUG   HandlerThread:20178 [meta.py:_save_pip():72] save pip done
2022-01-09 18:44:18,646 DEBUG   HandlerThread:20178 [meta.py:probe():252] probe done
2022-01-09 18:47:15,434 WARNING MainThread:20178 [internal.py:wandb_internal():146] Internal process interrupt: 1
2022-01-09 18:47:30,907 WARNING MainThread:20178 [internal.py:wandb_internal():146] Internal process interrupt: 2
2022-01-09 18:47:30,907 ERROR   MainThread:20178 [internal.py:wandb_internal():149] Internal process interrupted.
2022-01-09 18:47:31,186 INFO    WriterThread:20178 [datastore.py:close():281] close: /content/tbcnn/wandb/offline-run-20220109_184414-1fylxmq7/run-1fylxmq7.wandb
2022-01-09 18:47:31,196 INFO    HandlerThread:20178 [handler.py:finish():731] shutting down handler
2022-01-09 18:47:31,817 INFO    SenderThread:20178 [sender.py:finish():1070] shutting down sender
2022-01-09 18:47:31,822 INFO    MainThread:20178 [internal.py:handle_exit():77] Internal process exited
